### PR TITLE
Port database backend to rocksdb to support warm-starting the server

### PR DESCRIPTION
**Pull request by kriswehner**
This is preparation for #6 which would let us get a consistent copy of the database using the rocksdb checkpoint mechanism.

This also brings in the dependency on gorocksdb.

### CODE REVIEW

**Comment by gbrail** [comment]
I like the direction of this and it makes sense to me. But I'll need some time while I travel this week to look at it carefully and adapt things like the Docker build to it.

**Comment by gbrail** [comment]
While I love the idea of an "embedded build" for rocksdb support, in practice it seems to be a pain in the rear. But I want to make this a repeatable build, including Docker, before actually merging this.

We have two choices:

1) We can rely on the embedded rocksdb packages from CockroachDB, and require that people pass the "embed" tag on every build.

2) We can rely on having rocksdb on the local box, which is easier for us all once it's install, but it means that getting it in production is harder because RocksDB has to be there first. This isn't a huge issue for us because we typically run in Docker but it could complicate production deployments for others, since RocksDB isn't there in every package system and typically has to be rebuilt from source. Plus, it doesn't run on Alpine Linux, at least not a few months ago.

I'm leaning toward the second, with something in the build process to warn people when they have the wrong version.

**Comment by kriswehner** [comment]
We'd favor the second. We've already got a simple docker build going for it, as we always run in docker as well.

**Comment by gbrail** [comment]
Dealing with all the Docker stuff took a while and it was a busy week. But it looks good now and despite the more complex build it cleaned up a lot of code. Thanks!

**Pull request merged**
