### PR TITLE
Add the pg code to make the xid 64 bit, and bump the protobuf

### PR DESCRIPTION
**Pull request by kriswehner**
This attempts to address https://github.com/apigee-labs/transicator/issues/4

I used a clone of the postgres code that does the 64 bit xid conversion with a few twists. Please excuse the copy & paste, but the convenience function I cloned is declared static. Everything seems to work correctly.

The one caveat is there seems to be a postgres crash bug in some circumstances when replicating, but I've confirmed I'm seeing the same behavior with & without my patch, so I think it's unrelated (and I will file separately).

### CODE REVIEW

**Comment by kriswehner** [comment]
My fault, there's some test fails in here that I'll address shortly.

**Comment by gbrail** [comment]
OK -- I'll hold off until you let me know that you're ready.

**Comment by kriswehner** [comment]
@gbrail I think we're clear. The test fails that were confusing me were all in the pgclient package and unrelated.

**Comment by gbrail** [comment]
Thanks!

**Pull request merged**
