### PR TITLE
Distribute PG timestamps in binary form

### PR DESCRIPTION
**Pull request by gbrail**

### CODE REVIEW

**Comment by gbrail** [comment]
googlebot, I authored them and I'm not sure what you mean.

**Comment by gbrail** [comment]
Ah -- some were written long ago under my "greg@apigee.com" email address. That address is also covered by the CLA.

**Comment by alexkhimich** [comment]
Wonder if anybody reviewed the code.
In general who reviews transicator code,?

**Comment by gbrail** [comment]
You and Sundar are good candidates!

On Thu, Dec 15, 2016 at 1:55 PM, Alexander Khimich <notifications@github.com
> wrote:

> Wonder if anybody reviewed the code.
> In general who reviews transicator code,?
>
> Sent from a tiny screen device.
>

**Pull request merged**
